export const SEARCH_ARTICULO = "SEARCH_ARTICULO";
export const SET_ALLDATA = "SET_ALLDATA";
export const SHOW_FORMREGISTER = "SHOW_FORMREGISTER";
export const DO_REGISTER = "DO_REGISTER";
export const SHOW_FORMUPDATE = "SHOW_FORMUPDATE";
export const UPDATE_ARTICULO = "UPDATE_ARTICULO";
export const DO_CANCEL = "DO_CANCEL";
